name: morning
on:
  schedule:
  - cron:  '0 23 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: master

    - name: sender
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./zaoan
